/**
 * Roles del sistema (2 niveles: alta = DIRECTORA, resto = ADMINISTRADOR/SECRETARIA)
 * DIRECTORA: acceso total
 * ADMINISTRADOR: registro de pagos, solvencias, registro de estudiantes
 * SECRETARIA: solo ver notas (consulta)
 */
export const ROLES = {
  DIRECTORA: 'DIRECTORA',
  ADMINISTRADOR: 'ADMINISTRADOR',
  SECRETARIA: 'SECRETARIA',
};

/** Quién puede ver cada recurso */
export const PERMISSIONS = {
  ESTUDIANTES_LISTA: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR, ROLES.SECRETARIA],
  ESTUDIANTES_REGISTRO: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR],
  ESTUDIANTES_MODIFICACION: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR],
  PAGOS_REGISTRO: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR],
  /** Solo consulta: listar pagos, historial, resumen (sin crear/editar) */
  PAGOS_VER: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR],
  SOLVENCIAS: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR],
  /** Notas: ver listado y detalle */
  NOTAS_VER: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR, ROLES.SECRETARIA],
  /** Notas: crear/editar */
  NOTAS_REGISTRO: [ROLES.DIRECTORA, ROLES.ADMINISTRADOR],
  USUARIOS_GESTION: [ROLES.DIRECTORA],
  REPORTES: [ROLES.DIRECTORA],
  RESPALDO: [ROLES.DIRECTORA],
};

/** Inscripción: 5 años, 2 secciones por año = 10 secciones, 13 aulas, 40 por sección */
export const INSCRIPTION = {
  YEARS: [1, 2, 3, 4, 5],
  SECTIONS_PER_YEAR: 2,
  TOTAL_SECTIONS: 10,
  CLASSROOMS_AVAILABLE: 13,
  MAX_STUDENTS_PER_SECTION: 40,
};
